# Generated by Django 4.2.2 on 2023-07-05 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='hojaVida',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('cedula', models.IntegerField(max_length=100, verbose_name='cedula')),
                ('nombres', models.CharField(max_length=50, verbose_name='nombres')),
                ('apellidos', models.CharField(max_length=70, verbose_name='apellidos')),
                ('correo', models.CharField(max_length=100, verbose_name='correo')),
                ('celular', models.IntegerField(max_length=100, verbose_name='celular')),
                ('mensage', models.CharField(max_length=200, verbose_name='mensage')),
            ],
        ),
    ]
