# Generated by Django 4.2.2 on 2023-07-11 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hojaDeVida', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hojavida',
            name='cedula',
            field=models.CharField(max_length=250, verbose_name='cedula'),
        ),
        migrations.AlterField(
            model_name='hojavida',
            name='celular',
            field=models.CharField(max_length=250, verbose_name='celular'),
        ),
        migrations.AlterField(
            model_name='hojavida',
            name='correo',
            field=models.EmailField(max_length=100, verbose_name='correo'),
        ),
    ]
