# Generated by Django 4.2.2 on 2023-07-16 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='planes',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('plan', models.CharField(max_length=100, verbose_name=' plan')),
                ('detalles', models.CharField(max_length=100, verbose_name='detalles')),
                ('precio', models.CharField(max_length=100, verbose_name='precio')),
            ],
        ),
    ]
