# Generated by Django 4.2.2 on 2023-06-30 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='curso',
            fields=[
                ('ID_hotario', models.AutoField(primary_key=True, serialize=False)),
                ('horario_am', models.CharField(max_length=100, verbose_name='horario am')),
                ('horario_pm', models.CharField(max_length=100, verbose_name='horario pm')),
                ('horario_descanso', models.CharField(max_length=100, verbose_name='horario descanso')),
            ],
        ),
    ]
